version: '3.7'

services:
  redis:
    image: redis:7.2.5
    container_name: redis
    # command: redis-server --requirepass $$PASSWORD
    ports:
      - "4006:6379"
    networks:
      - uat_network
    

networks:
  uat_network:
    driver: bridge
